### ISSUE TITLE
Trim URL must ignore schema.org domain

### ISSUE THREAD

**Issue by pascalicchio** [renatomarinho/laravel-page-speed#127]
Google does not validate structured data a page (JSON-LD) when schema.org domain is trimmed.

Example when PageSpeed is on:
`"@context": "//schema.org",`

It has to be:
`"@context": "https://schema.org",`

If fixed markdown can be used to improve page SEO

**Comment by bexvibi** [comment]
+1

**Comment by mst101** [comment]
This has also considerably slowed down my creation of pages with Laravel ;-)

**Comment by joaorobertopb** [comment]
Hi guys,

The "Trim Urls" middleware is keeping in version 2.0 of this package. However, we do not encourage it to be registered, since it presents a certain risk of breaking the application.

See Readme.md:

![middleware-1](https://user-images.githubusercontent.com/6556083/104785268-dc597e80-5768-11eb-9cbe-2afbe2820b11.png)

![middleware-2](https://user-images.githubusercontent.com/6556083/104785310-f4c99900-5768-11eb-949d-129fdc135f97.png)

Thanks!
