### ISSUE TITLE
Issue with select dropdown based on another dropdown

### ISSUE THREAD

**Issue by allaghi** [renatomarinho/laravel-page-speed#25]
Hi,
I use Jquery to make select dropdown based on another dropdown, and it was working fine , when I use this package it select dropdown based on another dropdown not working anymore . do you know why ?

Many Thanks

**Comment by renatomarinho** [comment]
Hi @allaghi, 

Can you send me an example code?

**Comment by kenzouno1** [comment]
I think your javascript code not validated.(Example missing `;` in end of line before `$('.b')`

Example run this code without minify (no problem occurred)

````
$('.a').click(function(){
console.log('a');
})
$('.b').click(function(){
console.log('b');
})
````
But in with inline code replaced to
````
$('.a').click(function(){console.log('a');})$('.b').click(function(){console.log('b');})
````
This code throw error message `Uncaught SyntaxError: Unexpected identifier` because two statements in one line but not have `;`  seperate they.

Always use `js linter` for your code.

**Comment by allaghi** [comment]
@kenzouno1 , check my code please

**Comment by allaghi** [comment]
I got it , there is no semi colon at the end of var base_url = '{{url()}}'
and I should omit comments . Thank you so much @kenzouno1
