### ISSUE TITLE
[Suggestion] Add support for HTTP/2 server push

### ISSUE THREAD

**Issue by mortenscheel** [renatomarinho/laravel-page-speed#41]
<p>Hi. Any plans on adding support for push?
It's already implemented here: <a href="https://github.com/JacobBennett/laravel-HTTP2ServerPush">https://github.com/JacobBennett/laravel-HTTP2ServerPush</a></p>

**Comment by joaorobertopb** [comment]
Hi @mortenscheel,
Thanks for suggestion.

We are currently focusing on bug fixes and the implementation of all filters.

**Comment by johnhearfield** [comment]
Just a note about server push: You shouldn't push all the assets, only the critical ones. So you would need to create a vendor config file where the user will add the assets they want pushing, instead of preloading everything.

[Heres some background on the issue](https://www.smashingmagazine.com/2017/04/guide-http2-server-push/#you-can-push-too-much-stuff) for readup

**Comment by lucasMesquitaBorges** [comment]
Hello!!
Thanks for your suggestion but we do not plan to perform these features in the laravel-page-speed package!
